openapi: "3.0.2"
info:
  title: NutriSight RESTful API
  description: OpenAPI for NutriSight
  version: "0.1"
  contact:
    name: Cakra Kusuma
    email: cakraairlangga@gmail.com
servers:
  # Real Domain taruh sini
  - url: https://ourapp-test

paths:
  /user:
    post:
      description: Make user account
      operationId: createUser
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                username:
                  type: string
                  example: johndoe345
                email:
                  type: string
                  example: johndoe@example.com
                password:
                  type: string
                  example: holidayThere28
                passwordConfirm:
                  type: string
                  example: holidayThere28
      responses:
        201:
          description: User account successfully created
        400:
          description: Invalid input
  /user/{id}:
    get:
      description: Get user by User Id
      operationId: getUserByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 20360670-3873-4a19-8a03-c2344c40f51d
      responses:
        200:
          description: Success Response
          content:
            "application/json":
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    example: ajab1avi1927310ks
                  name:
                    type: string
                    example: John Doe
                  username:
                    type: string
                    example: johndoe9986
    patch:
      description: Edit user account profile
      operationId: editUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 20360670-3873-4a19-8a03-c2344c40f51d
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                username:
                  type: string
                  example: johndoe345
      responses:
        201:
          description: User account successfully edited
        400:
          description: Invalid input
        404:
          description: User Id not found
    delete:
      description: Delete user account
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 20360670-3873-4a19-8a03-c2344c40f51d
      responses:
        201:
          description: User account successfully deleted
        400:
          description: Invalid input
        404:
          description: User Id not found

  
